platform :ios, '10.1'
use_frameworks!
target 'QingShanProject' do
pod 'AFNetworking', '~> 3.1.0'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'IQKeyboardManager', '~> 4.0.4'
pod 'BaiduMapKit'
pod 'JPush', '~> 2.1.8'
pod 'MJExtension'
pod 'MMDrawerController', '~> 0.5.7'
pod 'SDWebImage', '~> 4.0'
pod 'MJRefresh'
end
